version: "3.1"
services:
  git-everywhere:
    build: ./
    image: iasuma/git-everywhere
    container_name: git-everywhere
    restart: always
    volumes:
      - ~/.ssh/:/root/.ssh/:ro
      - ./config/:/var/work/config/
      - ./data/:/var/work/data/
      - ./res/:/var/work/res/
